### ISSUE TITLE
widget fails on npm start

### ISSUE THREAD

**Issue by eliavmaman** [kambi-sportsbook-widgets/match-overview-widget#1]
![image](https://user-images.githubusercontent.com/6911449/40367791-e78c98e6-5de2-11e8-8f8a-62038c0384ea.png)

**Comment by eliavmaman** [comment]
any one support that feature ?

**Comment by owain-stratton** [comment]
Hi,

Glomo supports this widget. 

Can you please provide your node and npm versions please, and a dump of your package.json?

Thanks

**Comment by eliavmaman** [comment]
node => v7.2.1
npm => 4.0.5

**Comment by eliavmaman** [comment]
fixed the issue , problem was lates Node (10.1.0), downgrade to 6.9.3 and works fine
