### ISSUE TITLE
SSL Certificate is more than 30 days old. Removing.

### ISSUE THREAD

**Issue by eliavmaman** [kambi-sportsbook-widgets/match-overview-widget#4]
@owain-stratton Can u please help?
 When i run npm start i get the error 
**SSL Certificate is more than 30 days old. Removing.**
How should i remove it or  renew it?

**Comment by eliavmaman** [comment]
? :)

**Comment by owain-stratton** [comment]
@eliavmaman 

You have two options. 

1. Run the widget without `https` by setting this to `false` https://github.com/kambi-sportsbook-widgets/match-overview-widget/blob/master/package.json#L34

2. If you are running with `https` you will need to allow self signed SSL for localhost. For example below screenshot for Google Chrome.

![screen shot 2018-09-13 at 10 03 17](https://user-images.githubusercontent.com/16498502/45475382-81e52900-b73c-11e8-80ae-a7501606ec5a.png)

**Comment by eliavmaman** [comment]
Hey @owain-stratton 
I've changed  the ssl to false and now i get another error.. on npm start
<img width="1020" alt="screen shot 2018-09-13 at 11 29 06 am" src="https://user-images.githubusercontent.com/6911449/45476716-5a945900-b748-11e8-84a0-275e09cb666a.png">

and it doesnt run..

**Comment by eliavmaman** [comment]
?

**Comment by owain-stratton** [comment]
@eliavmaman 

Unable to reproduce my end. 

I'm running node `v10.10.0`.

It seems a node related perhaps you can try upgrading node.

**Comment by eliavmaman** [comment]
Sorry it was 8080 port was stucked.
If it happenes to u on mac os , just do the following:
1. netstat -vanp tcp | grep 8080
2. kill -9 <pid>
