### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. when start the widget

### ISSUE THREAD

**Issue by eliavmaman** [kambi-sportsbook-widgets/match-overview-widget#5]
@owain-stratton  Hey.
This happens from time to time...
Any idea why?

<img width="1279" alt="screen shot 2018-09-26 at 2 41 57 pm" src="https://user-images.githubusercontent.com/6911449/46077706-82e57400-c19a-11e8-8bcd-e1dfde85ede1.png">

**Comment by eliavmaman** [comment]
@owain-stratton Thanks... thats worked perfectly ..
Is that api is more reliable ? can i go production with that one?

**Comment by owain-stratton** [comment]
That should be more reliable yes.

To note though that the `mockSetupData.json` is "mocking" the sportsbook configuration setup and is only used in standalone when running the widget outside the sportsbook. You will need to check your sportsbook configuration.

If you need to force specific apiVersion for this widget, then you can pass your current mockSetupData.json as `mockSetupData` key in the args. The check is performed in the `coreLibrary` here https://github.com/kambi-sportsbook-widgets/widget-core-library/blob/master/src/coreLibrary.js#L542

**Comment by eliavmaman** [comment]
Thanks again :)
